# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxyapi.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proxyapi.proto',
  package='proxyapi',
  syntax='proto3',
  serialized_options=b'Z\021proxyapi;proxyapi',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eproxyapi.proto\x12\x08proxyapi\x1a\x1bgoogle/protobuf/empty.proto\"4\n\x0fProxyApiOptions\x12\x0f\n\x07\x41\x64\x64ress\x18\x01 \x01(\t\x12\x10\n\x08\x43ommands\x18\x02 \x03(\t\":\n\x18ProxyApiProviderResponse\x12\x0f\n\x07Success\x18\x01 \x01(\x08\x12\r\n\x05\x45rror\x18\x10 \x01(\t\">\n\x08\x41piEvent\x12\x0f\n\x07\x43ommand\x18\x01 \x01(\t\x12\x0f\n\x07Request\x18\x02 \x01(\t\x12\x10\n\x08Response\x18\x03 \x01(\t2\xa6\x01\n\x08ProxyApi\x12K\n\x08Register\x12\x19.proxyapi.ProxyApiOptions\x1a\".proxyapi.ProxyApiProviderResponse\"\x00\x12M\n\nDisconnect\x12\x19.proxyapi.ProxyApiOptions\x1a\".proxyapi.ProxyApiProviderResponse\"\x00\x32U\n\x10ProxyApiConsumer\x12\x41\n\x11OnReceiveApiEvent\x12\x12.proxyapi.ApiEvent\x1a\x16.google.protobuf.Empty\"\x00\x42\x13Z\x11proxyapi;proxyapib\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_PROXYAPIOPTIONS = _descriptor.Descriptor(
  name='ProxyApiOptions',
  full_name='proxyapi.ProxyApiOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Address', full_name='proxyapi.ProxyApiOptions.Address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Commands', full_name='proxyapi.ProxyApiOptions.Commands', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=109,
)


_PROXYAPIPROVIDERRESPONSE = _descriptor.Descriptor(
  name='ProxyApiProviderResponse',
  full_name='proxyapi.ProxyApiProviderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Success', full_name='proxyapi.ProxyApiProviderResponse.Success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Error', full_name='proxyapi.ProxyApiProviderResponse.Error', index=1,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=169,
)


_APIEVENT = _descriptor.Descriptor(
  name='ApiEvent',
  full_name='proxyapi.ApiEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Command', full_name='proxyapi.ApiEvent.Command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Request', full_name='proxyapi.ApiEvent.Request', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Response', full_name='proxyapi.ApiEvent.Response', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=233,
)

DESCRIPTOR.message_types_by_name['ProxyApiOptions'] = _PROXYAPIOPTIONS
DESCRIPTOR.message_types_by_name['ProxyApiProviderResponse'] = _PROXYAPIPROVIDERRESPONSE
DESCRIPTOR.message_types_by_name['ApiEvent'] = _APIEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProxyApiOptions = _reflection.GeneratedProtocolMessageType('ProxyApiOptions', (_message.Message,), {
  'DESCRIPTOR' : _PROXYAPIOPTIONS,
  '__module__' : 'proxyapi_pb2'
  # @@protoc_insertion_point(class_scope:proxyapi.ProxyApiOptions)
  })
_sym_db.RegisterMessage(ProxyApiOptions)

ProxyApiProviderResponse = _reflection.GeneratedProtocolMessageType('ProxyApiProviderResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROXYAPIPROVIDERRESPONSE,
  '__module__' : 'proxyapi_pb2'
  # @@protoc_insertion_point(class_scope:proxyapi.ProxyApiProviderResponse)
  })
_sym_db.RegisterMessage(ProxyApiProviderResponse)

ApiEvent = _reflection.GeneratedProtocolMessageType('ApiEvent', (_message.Message,), {
  'DESCRIPTOR' : _APIEVENT,
  '__module__' : 'proxyapi_pb2'
  # @@protoc_insertion_point(class_scope:proxyapi.ApiEvent)
  })
_sym_db.RegisterMessage(ApiEvent)


DESCRIPTOR._options = None

_PROXYAPI = _descriptor.ServiceDescriptor(
  name='ProxyApi',
  full_name='proxyapi.ProxyApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=236,
  serialized_end=402,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='proxyapi.ProxyApi.Register',
    index=0,
    containing_service=None,
    input_type=_PROXYAPIOPTIONS,
    output_type=_PROXYAPIPROVIDERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Disconnect',
    full_name='proxyapi.ProxyApi.Disconnect',
    index=1,
    containing_service=None,
    input_type=_PROXYAPIOPTIONS,
    output_type=_PROXYAPIPROVIDERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROXYAPI)

DESCRIPTOR.services_by_name['ProxyApi'] = _PROXYAPI


_PROXYAPICONSUMER = _descriptor.ServiceDescriptor(
  name='ProxyApiConsumer',
  full_name='proxyapi.ProxyApiConsumer',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=404,
  serialized_end=489,
  methods=[
  _descriptor.MethodDescriptor(
    name='OnReceiveApiEvent',
    full_name='proxyapi.ProxyApiConsumer.OnReceiveApiEvent',
    index=0,
    containing_service=None,
    input_type=_APIEVENT,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROXYAPICONSUMER)

DESCRIPTOR.services_by_name['ProxyApiConsumer'] = _PROXYAPICONSUMER

# @@protoc_insertion_point(module_scope)
