// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: proxyapi.proto

package proxyapi

import (
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ProxyApiOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Commands []string `protobuf:"bytes,2,rep,name=Commands,proto3" json:"Commands,omitempty"`
}

func (x *ProxyApiOptions) Reset() {
	*x = ProxyApiOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxyapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyApiOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyApiOptions) ProtoMessage() {}

func (x *ProxyApiOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proxyapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyApiOptions.ProtoReflect.Descriptor instead.
func (*ProxyApiOptions) Descriptor() ([]byte, []int) {
	return file_proxyapi_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyApiOptions) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ProxyApiOptions) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

type ProxyApiProviderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Error   string `protobuf:"bytes,16,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *ProxyApiProviderResponse) Reset() {
	*x = ProxyApiProviderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxyapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyApiProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyApiProviderResponse) ProtoMessage() {}

func (x *ProxyApiProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proxyapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyApiProviderResponse.ProtoReflect.Descriptor instead.
func (*ProxyApiProviderResponse) Descriptor() ([]byte, []int) {
	return file_proxyapi_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyApiProviderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProxyApiProviderResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ApiEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command  string `protobuf:"bytes,1,opt,name=Command,proto3" json:"Command,omitempty"`
	Request  string `protobuf:"bytes,2,opt,name=Request,proto3" json:"Request,omitempty"`
	Response string `protobuf:"bytes,3,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *ApiEvent) Reset() {
	*x = ApiEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxyapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiEvent) ProtoMessage() {}

func (x *ApiEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proxyapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiEvent.ProtoReflect.Descriptor instead.
func (*ApiEvent) Descriptor() ([]byte, []int) {
	return file_proxyapi_proto_rawDescGZIP(), []int{2}
}

func (x *ApiEvent) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ApiEvent) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *ApiEvent) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_proxyapi_proto protoreflect.FileDescriptor

var file_proxyapi_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x70, 0x69, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x78, 0x79,
	0x41, 0x70, 0x69, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73,
	0x22, 0x4a, 0x0a, 0x18, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x41, 0x70, 0x69, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x5a, 0x0a, 0x08,
	0x41, 0x70, 0x69, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa6, 0x01, 0x0a, 0x08, 0x50, 0x72, 0x6f,
	0x78, 0x79, 0x41, 0x70, 0x69, 0x12, 0x4b, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f,
	0x78, 0x79, 0x41, 0x70, 0x69, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x22, 0x2e, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x41, 0x70, 0x69,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x41, 0x70, 0x69, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x22, 0x2e, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x41, 0x70, 0x69, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x32, 0x55, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x41, 0x70, 0x69, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x11, 0x4f, 0x6e, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x41, 0x70, 0x69, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x69, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x61, 0x70, 0x69, 0x3b, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proxyapi_proto_rawDescOnce sync.Once
	file_proxyapi_proto_rawDescData = file_proxyapi_proto_rawDesc
)

func file_proxyapi_proto_rawDescGZIP() []byte {
	file_proxyapi_proto_rawDescOnce.Do(func() {
		file_proxyapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_proxyapi_proto_rawDescData)
	})
	return file_proxyapi_proto_rawDescData
}

var file_proxyapi_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proxyapi_proto_goTypes = []interface{}{
	(*ProxyApiOptions)(nil),          // 0: proxyapi.ProxyApiOptions
	(*ProxyApiProviderResponse)(nil), // 1: proxyapi.ProxyApiProviderResponse
	(*ApiEvent)(nil),                 // 2: proxyapi.ApiEvent
	(*empty.Empty)(nil),              // 3: google.protobuf.Empty
}
var file_proxyapi_proto_depIdxs = []int32{
	0, // 0: proxyapi.ProxyApi.Register:input_type -> proxyapi.ProxyApiOptions
	0, // 1: proxyapi.ProxyApi.Disconnect:input_type -> proxyapi.ProxyApiOptions
	2, // 2: proxyapi.ProxyApiConsumer.OnReceiveApiEvent:input_type -> proxyapi.ApiEvent
	1, // 3: proxyapi.ProxyApi.Register:output_type -> proxyapi.ProxyApiProviderResponse
	1, // 4: proxyapi.ProxyApi.Disconnect:output_type -> proxyapi.ProxyApiProviderResponse
	3, // 5: proxyapi.ProxyApiConsumer.OnReceiveApiEvent:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proxyapi_proto_init() }
func file_proxyapi_proto_init() {
	if File_proxyapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proxyapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyApiOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxyapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyApiProviderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxyapi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proxyapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proxyapi_proto_goTypes,
		DependencyIndexes: file_proxyapi_proto_depIdxs,
		MessageInfos:      file_proxyapi_proto_msgTypes,
	}.Build()
	File_proxyapi_proto = out.File
	file_proxyapi_proto_rawDesc = nil
	file_proxyapi_proto_goTypes = nil
	file_proxyapi_proto_depIdxs = nil
}
